blank_issues_enabled: false
contact_links:
  - name: "💬 Preguntas y Comunidad / Community Discussions"
    url: "https://github.com/SamuTecYT/ORAS-MMO/discussions"
    about: "¿Buscas amigos para jugar o tienes dudas sobre la configuración? ¡Únete a las discusiones de la comunidad!"
